(setq my-environment 'work)
(setq my-home-dir "/home/jli/")
(setq my-db-dir (concat my-home-dir "db/"))
(setq my-backup-dir (concat my-home-dir "backup/"))
(setq my-site-lisp-dir (concat my-home-dir "site-lisp/"))
(setq my-org-dir (concat my-home-dir "org/"))
(setq my-org-notes-dir (concat my-org-dir "notes/"))
(setq my-org-db-dir (concat my-org-dir "db/"))
(setq my-org-babel-dir (concat my-org-db-dir "babel/"))
(setq my-org-reminders-file (concat my-org-dir "reminder/reminders.org"))
(setq my-org-code-bookmark-file (concat my-org-notes-dir "emacs_links.org"))
(setq my-org-checklist-file (concat my-org-db-dir "general/checklist.org"))
(add-to-list 'load-path "~/config/emacs")
(add-to-list 'load-path my-site-lisp-dir)
(require 'init-core)
(require 'init-keybindings)
(require 'init-lib)
(require 'init-packages)
(require 'init-ui)
(require 'init-org)
;(require 'init-dired)
(require 'init-shell)
;(require 'init-elisp)
;; (require 'init-tramp)
;; (require 'init-magit)
;; (require 'init-work)
;; (require 'init-docker)
;; (require 'init-tmux)
(require 'init-snippets)
;; (require 'init-c++)
;; (require 'init-tabbar)
;; (require 'tb)
;; (require 'init-terminal)

;; (require 'init-postgres)

;; (require 'config-macros)
;; (require 'config-python)
(provide 'init)

